# Generated by Django 3.2.6 on 2021-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cursoid', models.IntegerField(db_column='CursoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('nivel', models.IntegerField(db_column='Nivel')),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('deptoid', models.IntegerField(db_column='DeptoID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('director', models.CharField(db_column='Director', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesorid', models.IntegerField(db_column='ProfesorID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('direccion', models.CharField(db_column='Direccion', max_length=100)),
                ('telefono', models.IntegerField(db_column='Telefono')),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
    ]
