# Generated by Django 3.2.6 on 2021-11-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsuario',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=15)),
            ],
        ),
    ]
